create sequence hibernate_sequence start with 1 increment by 1

    create table GameResult (
       id bigint not null,
        player varchar(255) not null,
        solved boolean not null,
        primary key (id)
    )
create sequence hibernate_sequence start with 1 increment by 1

    create table GameResult (
       id bigint not null,
        player varchar(255) not null,
        solved boolean not null,
        primary key (id)
    )
create sequence hibernate_sequence start with 1 increment by 1

    create table GameResult (
       id bigint not null,
        player varchar(255) not null,
        solved boolean not null,
        primary key (id)
    )
create sequence hibernate_sequence start with 1 increment by 1

    create table GameResult (
       id bigint not null,
        player varchar(255) not null,
        solved boolean not null,
        primary key (id)
    )
create sequence hibernate_sequence start with 1 increment by 1

    create table GameResult (
       id bigint not null,
        player varchar(255) not null,
        solved boolean not null,
        primary key (id)
    )
create sequence hibernate_sequence start with 1 increment by 1

    create table GameResult (
       id bigint not null,
        player varchar(255) not null,
        solved boolean not null,
        primary key (id)
    )
create sequence hibernate_sequence start with 1 increment by 1

    create table GameResult (
       id bigint not null,
        player varchar(255) not null,
        solved boolean not null,
        primary key (id)
    )
create sequence hibernate_sequence start with 1 increment by 1

    create table GameResult (
       id bigint not null,
        player varchar(255) not null,
        solved boolean not null,
        primary key (id)
    )
create sequence hibernate_sequence start with 1 increment by 1

    create table GameResult (
       id bigint not null,
        player varchar(255) not null,
        solved boolean not null,
        primary key (id)
    )
create sequence hibernate_sequence start with 1 increment by 1

    create table GameResult (
       id bigint not null,
        player varchar(255) not null,
        solved boolean not null,
        primary key (id)
    )
create sequence hibernate_sequence start with 1 increment by 1

    create table GameResult (
       id bigint not null,
        player varchar(255) not null,
        solved boolean not null,
        primary key (id)
    )
create sequence hibernate_sequence start with 1 increment by 1

    create table GameResult (
       id bigint not null,
        player varchar(255) not null,
        solved boolean not null,
        primary key (id)
    )

    create table GameResult (
       id bigint generated by default as identity,
        player varchar(255) not null,
        solved boolean not null,
        primary key (id)
    )

    create table GameResult (
       id bigint not null,
        player varchar(255) not null,
        solved boolean not null,
        primary key (id)
    )

    create table GameResult (
       id bigint not null,
        player varchar(255) not null,
        solved boolean not null,
        primary key (id)
    )

    create table GameResult (
       id bigint generated by default as identity,
        player varchar(255) not null,
        solved boolean not null,
        primary key (id)
    )

    create table GameResult (
       id bigint generated by default as identity,
        player varchar(255) not null,
        solved boolean not null,
        primary key (id)
    )

    create table GameResult (
       id bigint generated by default as identity,
        player varchar(255) not null,
        solved boolean not null,
        primary key (id)
    )

    create table GameResult (
       id bigint generated by default as identity,
        player varchar(255) not null,
        solved boolean not null,
        primary key (id)
    )

    create table GameResult (
       id bigint generated by default as identity,
        player varchar(255) not null,
        solved boolean not null,
        primary key (id)
    )

    create table GameResult (
       id bigint generated by default as identity,
        player varchar(255) not null,
        solved boolean not null,
        primary key (id)
    )

    create table GameResult (
       id bigint generated by default as identity,
        player varchar(255) not null,
        solved boolean not null,
        primary key (id)
    )
